### ISSUE TITLE
Please upgrade to 1.8.0

### ISSUE THREAD

**Issue by swftvsn** [catdad-experiments/libheif-js#1]
Hi!

Thank you for the wonderful work to push libheif to NPM. Can you compile a new version, 1.8.0 that should be tagged today? It contains some fixes that prevent converting some of ios made heics.

Thanks!

(Btw, if you can publish the container spec you use to do the emscripten build it would be really nice!)

**Comment by catdad** [comment]
Yeah, I'll be able to release it later today. Also, all of the automation is already in this repo, I don't have any part of it private or anything

**Comment by catdad** [comment]
Sorry, I lied (it's been a while since I've looked at this). The actual compiling happens in https://github.com/catdad-experiments/libheif-emscripten so you can take a look there for how it is done

**Comment by catdad** [comment]
Version 1.8.0 is out now

**Comment by swftvsn** [comment]
Thank you for your hard work!
