### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by jlarmstrongiv** [catdad-experiments/libheif-js#11]
According to https://github.com/strukturag/libheif, libheif now supports the AVIF file format.  Since this repo (and it’s associated packages heic-cli, heic-convert, heic-decode) depend on libheif, did they automatically receive AVIF support too?  Anyway, thank you for making these packages 😄

**Comment by catdad** [comment]
Unfortunately, no. AVIF is not supported in the web version of libheif. And it is unlikely to be supported. You can find out more about that here: https://github.com/catdad-experiments/libheif-emscripten/issues/15
