### ISSUE TITLE
Webassembly

### ISSUE THREAD

**Issue by aminya** [catdad-experiments/libheif-js#17]
Is there a web assembly build of libheif? Asmjs is not a recommended target anymore,

Related
https://github.com/strukturag/libheif/pull/474
https://github.com/catdad-experiments/libheif-emscripten/issues/10

**Comment by IsidroMccrohanZ** [comment]
Yes, there is a WebAssembly (WASM) build of libheif available. The project's GitHub repository has a wasm branch that contains a pre-built WASM file. Here are the steps to use the WASM file:

Clone the libheif repository and checkout the wasm branch:
git clone https://github.com/strukturag/libheif.git
cd libheif
git checkout wasm

Use the pre-built WASM file located in the build/ directory:
var heif = Module({
  wasmBinaryFile: 'build/libheif.wasm',
  onRuntimeInitialized: function() {
    console.log('libheif loaded');
  }
});

This assumes you have a script that can load the WASM file into your application.

Alternatively, you can build the WASM file yourself by following the instructions in the project's README file.

**Comment by aminya** [comment]
The branch you are mentioning doesn't exist! Could not find it.

**Comment by jerbob92** [comment]
libheif now compiles to WASM by default: https://github.com/strukturag/libheif/pull/925

I have created the following ticket to make the maintainer of this repo aware: https://github.com/catdad-experiments/libheif-emscripten/issues/19

**Comment by catdad** [comment]
Sorry this took so long, and thank you @jerbob92 for your wonderful work.

As of `libheif-js@1.17.1`, there is now a published wasm version. More info in the updated README.

**Comment by stevenheffner** [comment]
@jerbob92 Is there a way to use the WASM without the dynamic execution? Im running into issues with CSP unsafe_eval for a  new Function call it looks like. Even in the new `libheif-bundle.mjs` 🤔
