### ISSUE TITLE
Additional Functionality

### ISSUE THREAD

**Issue by dukesook** [catdad-experiments/libheif-js#20]
It looks like libheif-js does a great job decoding a HEIF image, but there are many additional functions listed in the [libheif](https://github.com/strukturag/libheif) library. Are there plans to extend libheif-js to include more of those functions? Do these things transfer well into a web application? Or is this more of an experimental repository as suggested by the name "catdata-experiments"?

**Comment by catdad** [comment]
This module compiles and distributes the web version available directly from [`libheif`](https://github.com/strukturag/libheif). They have provided this code for a while, but you always had to build it yourself, which not everyone can or wants to spend time doing. So in this project, I do it and make it available to everyone through a quick npm package install.

As my time to contribute to the core `libheif` project is limited, the best way to discuss getting more functionality into the web version is to file in issue there. Any new functionality accepted into `libheif`'s web package will automatically make it's way into the `libheif-js` module published to npm.

**Comment by dukesook** [comment]
Great, thank you. In that case, I'll look into contributing to the core `libheif`.
