### ISSUE TITLE
Error: libheif.HeifDecoder is not a constructor

### ISSUE THREAD

**Issue by dukesook** [catdad-experiments/libheif-js#22]
I'm trying to run libheif.js directly into an HTML page, but I'm getting the following error: *libheif.HeifDecoder is not a constructor*. Any ideas on what the problem is?

index.html
```HTML
<script type="module" src="image_parser.js"></script>
<script type="module"> 
   import libheif from 'https://cdn.jsdelivr.net/npm/libheif-js@1.17.1/libheif-wasm/libheif-bundle.mjs'; 
</script>

```
image_parser.js
```js
import libheif from 'https://cdn.jsdelivr.net/npm/libheif-js@1.17.1/libheif-wasm/libheif-bundle.mjs';
const decoder = new libheif.HeifDecoder();
```

**Comment by stevenheffner** [comment]
@dukesook 

If you are pulling from the libheif-bundle you need to init the module with a function call.

```
  const libheif = window.libheif()

  const decoder = new libheif.HeifDecoder()
```

You can see this is done for you in wasm bundle.js

`module.exports = require('./libheif-wasm/libheif-bundle.js')();`

**Comment by dukesook** [comment]
Thanks @stevenheffner, but they gave me the following error: 

`window.libheif is not a function`

I posted my attempt at using libheif.js [here](https://github.com/dukesook/use_libheif-js). Are there any glaring mistakes?

**Comment by catdad** [comment]
@dukesook here's a codepen I made showing off how to use the esmodule version from jsdelivr: https://codepen.io/catdad/pen/jOJpVJV

Let me know if this helps or if you still have any issues.

**Comment by Duefectu** [comment]
It worked for me!
Thank you!

**Comment by dukesook** [comment]
@d-hand 
The example worked, thank you!
