### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by Duefectu** [catdad-experiments/libheif-js#24]
Is there any way it can work on Android.
Throws exception: Could not parse HEIF file,Invalid input: No 'ftyp' box".

On Windows it works perfectly.

Thanks for your excellent work!

**Comment by catdad** [comment]
I use this module on Android all the time. The error you are seeing indicates the file is not actually a HEIC image. Can you provide a file where you see this to confirm?

How you get the file off of the source matters. For example, Apple often pre-converts the file to jpeg when sharing it but keeps the file extension as .HEIC just to make every non-iPhone user's life worse. If this is a common workflow for your use case, I would suggest adding file type validation before converting your files.

**Comment by Duefectu** [comment]
La misma aplicación funciona bien con EDGE desde Windows.
Atacando al mismo servidor desde Android falla. Estoy usando WebView, quizás ese sea el problema...
El fichero .heic es el mismo que funciona en Windows, y está tomado con un Android.

[_TEST.zip](https://github.com/catdad-experiments/libheif-js/files/15010956/_TEST.zip)

**Comment by Duefectu** [comment]
Confirmed, it's the Xamarin WebView.
Fortunately, with the MAUI WebView it works perfectly!
Thank you very much!
