### ISSUE TITLE
Is there a way to generate a heic/heif file using this library?

### ISSUE THREAD

**Issue by Xheldon** [catdad-experiments/libheif-js#28]
I am working on a heic/heif compression tool using the Electron tech stack. I want to use libheif-js to compress a buffer read from the hard drive by `node:fs` to a specified value and then output it to a given path.

I found that the library only has the `new libheif.HeifDecoder()` method to read files correctly, but it lacks the `new libheif.HeifEncoder()` method to generate a heic/heif file. Is my understanding correct?

Is there any way to generate a heic/heif file?

Thx!

**Comment by catdad** [comment]
There is no encoding in the javascript version: https://github.com/strukturag/libheif/issues/113

Since you are writing an Electron desktop application, I would definitely recommend calling native binaries rather than using the javascript version.
