### ISSUE TITLE
Module['ENVIRONMENT'] value is not valid

### ISSUE THREAD

**Issue by lgv-0** [catdad-experiments/libheif-js#3]
One of my team members is having trouble using this locally, but on my machine and a AWS Deployment of our Node application, it works fine.

The error being generated is the following:
> \\node_modules\\libheif-js\\libheif\\libheif.js:1
> var Module=typeof Module!=="undefined"?Module:{};((function(){var Module={print:(function(text){text=Array.prototype.slice.call(arguments).join(" ");console.log(text)}),printErr:(function(text){text=Array.prototype.slice.call(arguments).join(" ");console.error(text)}),canvas:{},noInitialRun:true};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|W

> Error: write EOF
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)

Any guidance on this would be appreciated, thanks for your time.

**Comment by catdad** [comment]
This error doesn't seem familiar... it's unclear what the error even is from what is shown. Can you tell me more about the environment your team member is using. What OS, version of node, version of this library, etc. What is being done when this error happens? The error also appears to be an EOF for a network socket? Is an entire image heif file being provided?

**Comment by lgv-0** [comment]
Thanks for the quick response, actually this error was just telling us there was an error on line 1 (my bad!), which is the entire file, so we beautified it and we're failing under ENVIRONMENT_IS_NODE (Line 81 for us.)

```
process["on"]("uncaughtException", (function(ex) {
            if (!(ex instanceof ExitStatus)) {
                throw ex
            }
}));
```

Currently, we're hitting this on Windows 10, Node 12.19 - but I'm thinking this is just telling us there was an error somewhere somehow, not the origination of the error

**Comment by catdad** [comment]
Hmm... yeah, it look like emscripten adds this code and just rethrows unhandled exceptions (https://github.com/emscripten-core/emscripten/issues/7855). This would mean that the error could be coming from anywhere, not even just this library. I did run the tests on Windows 10 with node 12.19.0 specifically, and that all seems to pass. If it is to be this library, my guess is that it might be specific to an image. I am guessing you've tried different images, and also tried converting the same image between this affected environment and other environments where it works?

The only other hint would be the EOF that you originally included, most likely from a socket somewhere else in your application. Unfortunately, socket errors never have a good stack trace. You might be able to use `npx cross-env NODE_DEBUG=net node my-app.js` to get *a lot* of detailed usage info that might help figure out the issue.

**Comment by lgv-0** [comment]
This is right on, thanks for your help. I was initially confused because I haven't had an entire file dump as an error message haha - it's actually originating from something entirely different, _when this library isn't even being used_. Hopefully this will help someone in the future, fastest way to get the actual error was to comment out the require() to find it was from another component entirely.

Thanks again!
