### ISSUE TITLE
Images from Apple devices are distorted when parsed by libheif-js

### ISSUE THREAD

**Issue by kaatt** [catdad-experiments/libheif-js#4]
Original image:
<img width="200" alt="" src="https://user-images.githubusercontent.com/10688522/102064068-dcd6c080-3e1c-11eb-9b09-83dbe76050c9.png">

Converted to JPG with `npx heic-cli < IMG_8099.heic > IMG_8099.heic.jpg`:
<img width="200" alt="" src="https://user-images.githubusercontent.com/10688522/102068534-8b313480-3e22-11eb-8dab-7905f7c57bed.png">

Download HEIC image: [IMG_8099.heic.zip](https://github.com/catdad-experiments/libheif-js/files/5688050/IMG_8099.heic.zip) (it's in zip because GitHub doesn't allow HEIC uploads)

Noticed the same issue with https://alexcorvi.github.io/heic2any/

Maybe libheif needs updating or an issue in libheif?

**Comment by kaatt** [comment]
Cross-posted https://github.com/strukturag/libheif/issues/401

**Comment by catdad** [comment]
1.10.0 is out now and it should fix this issue
